apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opencode-server.fullname" . }}-config
data:
  opencode.json: |-
{{ .Files.Get "files/opencode.json" | indent 4 }}
  AGENTS.md: |-
{{ .Files.Get "files/AGENTS.md" | indent 4 }}
{{- range $path, $_ := .Files.Glob "files/agents/*.md" }}
  {{ base $path }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}
{{- range $path, $_ := .Files.Glob "files/skills/*/SKILL.md" }}
  {{ trimPrefix "files/" $path | replace "/" "-" }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}
