fullnameOverride: opencode

image:
  repository: ghcr.io/anomalyco/opencode
  tag: "1.18.29@sha256:ecc3bf96ee55dad226d9cde50d79aaa8a1215c47860c0fcdc71570461bf438b8"

persistence:
  existingClaim: opencode-home
  artifactsExistingClaim: opencode-artifacts

secrets:
  kimi: opencode-kimi
  minimax: opencode-minimax
  openaiAuth: opencode-openai-auth
  serverAuth: opencode-server-auth
  zai: opencode-zai
