fullnameOverride: opencode

image:
  repository: ghcr.io/anomalyco/opencode
  tag: "1.18.23@sha256:182959d5ae507fa2b3dcfd6ec247ad625b7f15539977dd0620f43f7e24c78229"

persistence:
  existingClaim: opencode-home
  artifactsExistingClaim: opencode-artifacts

secrets:
  kimi: opencode-kimi
  minimax: opencode-minimax
  openaiAuth: opencode-openai-auth
  serverAuth: opencode-server-auth
  zai: opencode-zai
