apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent-pipe-uploader.fullname" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- include "agent-pipe-uploader.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "agent-pipe-uploader.labels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
